### ISSUE TITLE
Request options to control the list of actions available to users

### ISSUE THREAD

**Issue by andrew-gardener** [abelardopardo/ontask_b#112]
Would greatly help if there where some environment variables to enable/disable actions that are available to users. The UBC use case is that we can only allow Canvas Messages (no emails) so hiding the other options would be helpful

**Comment by abelardopardo** [comment]
Trying to get a sense of how committed is this. Would it be enough if the tool only prevents the creation of these actions? The reason for the question is because preventing creation is checked in a single place whereas banning the presence of some actions requires numerous checks in a large number of places in the platform (import, edit, run, etc.) What do you think?

**Comment by abelardopardo** [comment]
Fixed in release B.4.1
