### ISSUE TITLE
click workflow detail page will sometimes direct to workflow index page or direct to other workflow's detail page

### ISSUE THREAD

**Issue by cherrie12** [abelardopardo/ontask_b#141]
I met an error when using ontask. After I upload the data and want to check the content, it sometimes direct me to the workflow index page. It means the session cannot get the workflow_id. And sometimes it will direct to other workflow’s page. I have checked the code and found it maybe caused by lock function. Do you know why cause this? I have no idea about that.

**Comment by cherrie12** [comment]
<img width="1625" alt="WeChat9ce3f8fcc8be137071cd207071029446" src="https://user-images.githubusercontent.com/31469814/54965921-8a50d300-4fad-11e9-98ae-4ec7b394d184.png">
<img width="1588" alt="WeChatcf6862540fad0ab06c94f4b9b6b70a8a" src="https://user-images.githubusercontent.com/31469814/54965928-8de45a00-4fad-11e9-951d-1f0db2ffa8d3.png">
We can see that when I click the table information. It's direct to other workflow's table page.

**Comment by abelardopardo** [comment]
Thank you for the comment.

Yes, the problem is probably due to the fact that there are several concurrent sessions with the same user accessing the same workflow. When this is the case, the workflow gets "locked" with the user name and the session id. If the user then closes the browser and opens it again and tries to access the same workflow, the session is different and therefore, the workflow is not available. OnTask has a 30 min timeout for sessions, so in that case, the workflow will be available again after that time (unlocked). This feature is needed to allow users to share workflows with other users, but also to prevent concurrent changes from parallel sessions.

I recommend to use the logout functionality, or simply visit the home page after a user is done handling a workflow. 

Regards.
