### ISSUE TITLE
potential to escalate 'at risk' students

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#158]
**Is your feature request related to a problem? Please describe.**
This is linked to an identified gap for us where the likelihood of contacting students through OnTask's electronic messaging feature is very low when working with groups of students who are displaying disengaged (at risk) behaviours

**Describe the solution you'd like**
IN the process of using OnTask's text conditions to identify the different cohorts of students an instructor might contact with different messages, the filtering matrix will highlight groups of students that are likely 'at risk.'  Example: in the hypothetical scenario below (see image), 3 datasets are being used to filter students: whether the student is repeating the course (blue), attending a required lab or tutorial (yellow), and the level of achievement on formative/low stakes assessments before a mid-term test (grey). 
![rubric for filtering students](https://user-images.githubusercontent.com/14169588/63408319-d3189500-c442-11e9-8432-2079f04a6707.png)
Those students that are failing the assessments, not attending as expected, and are either repeat or new students are displaying 'at risk' behaviours (red cells) and are also (in our experience to date) unlikely to respond to OnTask messages from the instructor. We would like the option for instructors to be able to 'escalate' these specific groups of students to whatever local process (mentors, student support service, Assoc Dean of Students, etc) might exist for handling or supporting disengaged/at-risk students. Within our institution, that escalation can occur via an email to a specific team or office. In the same way that OnTask currently allows an instructor to remove an individual email address from the final list of recipients, it would be ideal if an instructor can redirect a group of students (identified within the text conditions page - see image below) to an existing entity that is specifically tasked with and has the capacity to work with 'at risk' students. This also benefits the course instructor by reducing the workload represented by working with disengaged students and redirect it to the appropriate services that already exists to support these students.
![conditions showing at risk students](https://user-images.githubusercontent.com/14169588/63408897-217a6380-c444-11e9-9571-e6ff16d850f2.png)

**Describe alternatives you've considered**
Within the screenshot above, it might be ideal and simple for instructors to use an additional button (represented by the red exclamation button for clarity) at the bottom of a 'Conditions' tile that allowed them to escalate (redirect via email) the group(s) of identified students to the appropriate team/office/service.

**Comment by abelardopardo** [comment]
Thanks @leichtweis for the new scenario. We haven't considered this before, but it makes perfect sense as it is another type of action that can be derived from the data.

After considering this new scenario, I have a suggestion. Instead of overloading the operations in the same action (that is, instead of adding an "additional button"), my suggestion is to allow a new type of action that instead of sending a message to the student, it sends the list of students selected by the filter to a specific email address. Under this proposal, the platform would then have an additional action called "Escalate" (or something similar) that would allow to write a simple email and insert the list of students at some point in the middle of the text. This way, the email would look something line:

------
Dear student services.

Here is the list of students that we have identified as "at risk" following our previous conversations:

{{ FILTER_RESULT }}

Regards.
------

That action then can be executed (or scheduled!) as any other with the change that upon execution a new email address (in this case student services) will be required as the destination of the message.

Does this make sense? I think it embraces the scenario you describe it, but it casts it as another action instead of overloading an existing action.

Two more aspects would fit perfectly this new frame:

1) You would remove the students at risk from the personalized action with a filter.

2) You could clone that filter condition into the new action (submit to an email) and simply negate the condition, thus selecting the students excluded from the personalised action, and including that list in the email to student services.

Comments?

**Comment by leichtweis** [comment]
@abelardopardo this makes sense and would certainly be a welcome addition to the tool from our perspective. My suggestion to highlight or tag filtered cohorts based on the tiles in the "text conditions page" because a lot of our users find that visual an easy way to get a sense of the spread of student's engagement behaviours and where they "fall" in relation to the filtered data.

**Comment by abelardopardo** [comment]
Two new action types created to implement this.
