### ISSUE TITLE
'Send as' option

### ISSUE THREAD

**Issue by mylesblaney** [abelardopardo/ontask_b#186]
**Is your feature request related to a problem? Please describe.**
Some lectures do not want to send emails from their address. Creating a generic account is a workaround however can be problematic and confusing. We have encountered this on larger courses that have multiple instructors.

A 'send as' option would be useful to allow lectures to use a generic account. This could be visible in the 'Send email action' screen but would only be visible if a user has the correct permissions.

**Comment by leichtweis** [comment]
Hi @mylesblane, this was something discussed in issue #57 (closed) and was not something that Abelardo was keen to include in the core code (due to the obvious risks). We do provide this capability for just 2 very large courses at Auckland. In our local server, the code we wrote allows anyone assigned "staff status" in the DB Admin console --> users page to view an additional "From" email field along with Subject, cc:, & Bcc: fields. In our case, the course administrator can act as the proxy for each member of a large teaching team although the teachers still write all the emails (in advance of the comms date) and the reply address is still their university email. In this specific scenario, the individual instructors don't interact with the OnTask tool but leave that job to the course coordinator/admin. Hopefully, someone in your institution might be able to code this function and re-install it with each OnTask version upgrade. Let me know if you would like a copy of our code as an example and I will send or share that directly to you.

**Comment by mylesblaney** [comment]
Hi @leichtweis thanks for replying. Could we get a copy of the code?
