### ISSUE TITLE
upload/merge page

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#30]
The script for the upload function on the Upload/Merge page should be able to discern whether the file being uploaded is either CSV or Excel format. The need for two separate buttons to handle the two formats seems redundant. Could be reduced to a single 'upload/merge' button and potentially reduce some user confusion.

![upload-merge](https://user-images.githubusercontent.com/14169588/39974270-a1fa1aa0-577b-11e8-8669-e8cdeda3826b.png)

**Comment by abelardopardo** [comment]
The data requested for these two actions are different:
1) If a file is a CSV file, there is a possibility of specifying a number of lines to skip at the top and at the bottom. This is very useful when processing csv dumps produced by third party applications that have some prelude on top (stating the type of report) or some additional lines at the bottom. The form that appears after clicking in this link allows to enter these numbers. This option is not available if the format is XSL.

2) If a file is a XSL file, there is a possibility of specifying the sheet of the spreadsheet to read. This option is not available if the file is CSV.

So, for this reason I think it makes sense to keep both options, otherwise, an alternative would be to increase the number of steps by 1. The first step only requests the file and a second (new) step would request either the lines at the top/bottom to ignore (if CSV) or the name of the sheet (if excel). Then the rest of the steps would follow. I think this solution complicates the sequence of steps by one, while the double link solution seems a good tradeoff.

Happy to reopen if needed.
