### ISSUE TITLE
from email , CC email & BCC email functionality

### ISSUE THREAD

**Issue by leichtweis** [abelardopardo/ontask_b#57]
One of the functionalities we provided in the java version of SRES (v2) was for the sender email to be editable. This provided the opportunity for others to act as proxies for the course/unit coordinator or lecturer. we also included cc: and bcc: functionality. While Cc & Bcc specifically might not be needed with the workflow snapshot, logs and summary msgs in OnTask, the ability for the sender email address to be editable would be very useful for us. What is the potential for this functionality to be included in OnTask or did I not see the button?

_image from version 2 of SRES_
![sres v2 screenshot from email wysiwyg page](https://user-images.githubusercontent.com/14169588/42672548-c3d66732-86ba-11e8-8583-9850d5d37170.png)

**Comment by leichtweis** [comment]
is this something that we should code for within our local install or something you are considering for a future release?

**Comment by abelardopardo** [comment]
Good question. We need to think a bit more about this. Manipulating the "From" field is a bit tricky because it opens the door for impersonation and may have also consequences in terms of ruling email as spam (because the user sending it to the SMTP server is not the same one in the from). I would like to stick to this restriction

On the other hand, CC and BCC are definitively two fields that can be easily included. I'll pencil that down as something to implement.

**Comment by leichtweis** [comment]
Ok, its something we will implement locally as we have use cases where this function is required.

**Comment by abelardopardo** [comment]
Fixed in version B.2.8.0
